CREATE OR REPLACE 
PROCEDURE "CANCEL_CUSTOMER_ORDER_ITEM" (ORDER_ITME_ID IN VARCHAR2, UPDATOR IN VARCHAR2, 
	RESULT_UNFINISHED_WOS OUT SYS_REFCURSOR)
AS
	ORDER_ID T_PLA_CUSTOMER_ORDER."ID"%TYPE;
	NOW CONSTANT TIMESTAMP:=SYSDATE;
	CANCELED CONSTANT VARCHAR2(10):='CANCELED';
	TO_CONFIRM CONSTANT VARCHAR2(15):='TO_CONFIRM';
	TO_DO CONSTANT VARCHAR2(10):='TO_DO';
	TO_AUDIT CONSTANT VARCHAR2(10):='TO_AUDIT';
	IN_PROGRESS CONSTANT VARCHAR2(15):='IN_PROGRESS';

BEGIN
	-- 初始化变量
	SELECT CUSTOMER_ORDER_ID INTO ORDER_ID FROM T_PLA_CUSTOMER_ORDER_ITEM WHERE "ID" = ORDER_ITME_ID;

	-- 更新CUSTOMER_ORDER_ITEM
	UPDATE T_PLA_CUSTOMER_ORDER_ITEM 
		SET STATUS = CANCELED, MODIFY_USER_CODE = UPDATOR, MODIFY_TIME = NOW
	WHERE "ID" = ORDER_ITME_ID;
	
	-- 所有CUSTOMER_ORDER_ITEM已取消则更新CUSTOMER_ORDER
	UPDATE T_PLA_CUSTOMER_ORDER o 
		SET o.STATUS = CANCELED, o.MODIFY_USER_CODE = UPDATOR, o.MODIFY_TIME = NOW
	WHERE o."ID" = ORDER_ID 
		AND (
			SELECT COUNT(i.ID) FROM T_PLA_CUSTOMER_ORDER_ITEM i WHERE i.CUSTOMER_ORDER_ID = ORDER_ID AND i.STATUS != CANCELED
		) = 0;

	-- 修改相关CustomerOrderItemDec状态为已取消
	UPDATE T_PLA_CUSTOMER_ORDER_ITEM_DEC 
		SET STATUS = CANCELED, MODIFY_USER_CODE = UPDATOR, MODIFY_TIME = NOW
	WHERE ORDER_ITEM_ID = ORDER_ITME_ID;
	
	-- 修改相关CustomerOrderItemProDec状态为已取消
	UPDATE T_PLA_CU_ORDER_ITEM_PRO_DEC p
		SET p.STATUS = CANCELED, p.MODIFY_USER_CODE = UPDATOR, p.MODIFY_TIME = NOW
	WHERE EXISTS (
		SELECT d."ID" FROM T_PLA_CUSTOMER_ORDER_ITEM_DEC d WHERE p.ORDER_ITEM_DEC_ID = d."ID" AND d.ORDER_ITEM_ID = ORDER_ITME_ID
	);

	-- 修改相关OrderTask状态为已取消
	UPDATE T_PLA_ORDER_TASK t
		SET t.STATUS = CANCELED, t.MODIFY_USER_CODE = UPDATOR, t.MODIFY_TIME = NOW
	WHERE EXISTS (
		SELECT d."ID" FROM T_PLA_CU_ORDER_ITEM_PRO_DEC p, T_PLA_CUSTOMER_ORDER_ITEM_DEC d
		WHERE t.ORDER_ITEM_PRO_DEC_ID = p."ID" AND p.ORDER_ITEM_DEC_ID = d."ID" AND d.ORDER_ITEM_ID = ORDER_ITME_ID
	);
	
	-- 修改相关未生产的WorkOrder的状态为已取消
	UPDATE T_WIP_WORK_ORDER w
		SET w.STATUS = CANCELED, w.MODIFY_USER_CODE = UPDATOR, w.MODIFY_TIME = NOW
	WHERE EXISTS (
		SELECT d."ID" FROM T_PLA_ORDER_TASK t, T_PLA_CU_ORDER_ITEM_PRO_DEC p, T_PLA_CUSTOMER_ORDER_ITEM_DEC d
		WHERE w.WORK_ORDER_NO = t.WORK_ORDER_NO AND w.STATUS IN (TO_CONFIRM, TO_DO, TO_AUDIT)
			AND t.ORDER_ITEM_PRO_DEC_ID = p."ID" AND p.ORDER_ITEM_DEC_ID = d."ID" AND d.ORDER_ITEM_ID = ORDER_ITME_ID
	);

	-- 修改生产中的WorkOrder的已取消长度
	UPDATE T_WIP_WORK_ORDER w
		SET w.CANCEL_LENGTH = (
			SELECT SUM(t.TASK_LENGTH) FROM T_PLA_ORDER_TASK t, T_PLA_CU_ORDER_ITEM_PRO_DEC p, T_PLA_CUSTOMER_ORDER_ITEM_DEC d
			WHERE w.WORK_ORDER_NO = t.WORK_ORDER_NO
			AND t.ORDER_ITEM_PRO_DEC_ID = p."ID" AND p.ORDER_ITEM_DEC_ID = d."ID" AND d.ORDER_ITEM_ID = ORDER_ITME_ID
		), w.MODIFY_USER_CODE = UPDATOR, w.MODIFY_TIME = NOW
	WHERE EXISTS (
		SELECT d."ID" FROM T_PLA_ORDER_TASK t, T_PLA_CU_ORDER_ITEM_PRO_DEC p, T_PLA_CUSTOMER_ORDER_ITEM_DEC d
		WHERE w.WORK_ORDER_NO = t.WORK_ORDER_NO AND w.STATUS = IN_PROGRESS
			AND t.ORDER_ITEM_PRO_DEC_ID = p."ID" AND p.ORDER_ITEM_DEC_ID = d."ID" AND d.ORDER_ITEM_ID = ORDER_ITME_ID
	);

	--返回生产中的WorkOrder
	OPEN RESULT_UNFINISHED_WOS FOR 
	SELECT w."ID", w.WORK_ORDER_NO, w.EQUIP_CODE, w.ORDER_LENGTH, w.CANCEL_LENGTH
		FROM T_WIP_WORK_ORDER w
	WHERE EXISTS (
		SELECT d."ID" FROM T_PLA_ORDER_TASK t, T_PLA_CU_ORDER_ITEM_PRO_DEC p, T_PLA_CUSTOMER_ORDER_ITEM_DEC d
		WHERE w.WORK_ORDER_NO = t.WORK_ORDER_NO AND w.STATUS = IN_PROGRESS
			AND t.ORDER_ITEM_PRO_DEC_ID = p."ID" AND p.ORDER_ITEM_DEC_ID = d."ID" AND d.ORDER_ITEM_ID = ORDER_ITME_ID
	);

END;
