CREATE OR REPLACE 
PROCEDURE "DELETE_CUSTOMER_ORDER" (ORDER_ID_TO_DEL IN VARCHAR2, ORDER_ID_TO_ADD IN VARCHAR2, UPDATOR IN VARCHAR2)
AS
    ITEM_DEC_ID T_PLA_CUSTOMER_ORDER_ITEM_DEC.ID%TYPE;

    CURSOR mycursor is
        SELECT d.ID FROM T_PLA_CUSTOMER_ORDER_ITEM_DEC d
        WHERE EXISTS (
                        SELECT i."ID" FROM T_PLA_CUSTOMER_ORDER_ITEM i
                        WHERE d.ORDER_ITEM_ID = i."ID" AND i.CUSTOMER_ORDER_ID = ORDER_ID_TO_DEL
                      );
BEGIN
	-- 针对相同产品的orderItem，进行数量合并
	UPDATE T_PLA_CUSTOMER_ORDER_ITEM a 
		SET a.ORDER_LENGTH = a.ORDER_LENGTH + (
			SELECT d.ORDER_LENGTH FROM T_PLA_CUSTOMER_ORDER_ITEM d 
			WHERE d.CUSTOMER_ORDER_ID = ORDER_ID_TO_DEL AND a.SALES_ORDER_ITEM_ID = d.SALES_ORDER_ITEM_ID
		), a.MODIFY_USER_CODE = UPDATOR, a.MODIFY_TIME = SYSDATE
	WHERE a.CUSTOMER_ORDER_ID = ORDER_ID_TO_ADD;

  --删除CustomerOrderItemDec下的所有数据
  OPEN mycursor;
  LOOP
  FETCH mycursor INTO ITEM_DEC_ID;
  EXIT WHEN mycursor%NOTFOUND;     
      DELETE_CUS_ORDER_ITEM_DEC(ITEM_DEC_ID,UPDATOR,'0');
  END LOOP;
  CLOSE mycursor;

	-- 删除CustomerOrderItem
	DELETE FROM T_PLA_CUSTOMER_ORDER_ITEM WHERE CUSTOMER_ORDER_ID = ORDER_ID_TO_DEL;

	-- 删除CustomerOrder
	DELETE FROM T_PLA_CUSTOMER_ORDER WHERE ID = ORDER_ID_TO_DEL;
	
END;
