Fx.Slide=new Class({Extends:Fx,options:{mode:"vertical"},initialize:function(a,b){this.addEvent("complete",function(){(this.open=this.wrapper["offset"+this.layout.capitalize()]!=0)&&Browser.Engine.webkit419&&this.element.dispose().inject(this.wrapper)},!0);this.element=this.subject=$(a);this.parent(b);this.wrapper=this.element.retrieve("wrapper")||(new Element("div",{styles:$extend(this.element.getStyles("margin","position"),{overflow:"hidden"})})).wraps(this.element);this.element.store("wrapper",
this.wrapper).setStyle("margin",0);this.now=[];this.open=!0},vertical:function(){this.margin="margin-top";this.layout="height";this.offset=this.element.offsetHeight},horizontal:function(){this.margin="margin-left";this.layout="width";this.offset=this.element.offsetWidth},set:function(a){this.element.setStyle(this.margin,a[0]);this.wrapper.setStyle(this.layout,a[1]);return this},compute:function(a,b,c){var d=[];(2).times(function(e){d[e]=Fx.compute(a[e],b[e],c)});return d},start:function(a,b){if(!this.check(arguments.callee,
a,b))return this;this[b||this.options.mode]();var c=this.element.getStyle(this.margin).toInt(),d=this.wrapper.getStyle(this.layout).toInt(),e=[[c,d],[0,this.offset]],c=[[c,d],[-this.offset,0]],f;switch(a){case "in":f=e;break;case "out":f=c;break;case "toggle":f=this.wrapper["offset"+this.layout.capitalize()]==0?e:c}return this.parent(f[0],f[1])},slideIn:function(a){return this.start("in",a)},slideOut:function(a){return this.start("out",a)},hide:function(a){this[a||this.options.mode]();this.open=!1;
return this.set([-this.offset,0])},show:function(a){this[a||this.options.mode]();this.open=!0;return this.set([0,this.offset])},toggle:function(a){return this.start("toggle",a)}});
Element.Properties.slide={set:function(a){var b=this.retrieve("slide");b&&b.cancel();return this.eliminate("slide").store("slide:options",$extend({link:"cancel"},a))},get:function(a){if(a||!this.retrieve("slide"))(a||!this.retrieve("slide:options"))&&this.set("slide",a),this.store("slide",new Fx.Slide(this,this.retrieve("slide:options")));return this.retrieve("slide")}};
Element.implement({slide:function(a,b){var a=a||"toggle",c=this.get("slide"),d;switch(a){case "hide":c.hide(b);break;case "show":c.show(b);break;case "toggle":d=this.retrieve("slide:flag",c.open);c[d?"slideOut":"slideIn"](b);this.store("slide:flag",!d);d=!0;break;default:c.start(a,b)}d||this.eliminate("slide:flag");return this}});
Fx.Scroll=new Class({Extends:Fx,options:{offset:{x:0,y:0},wheelStops:!0},initialize:function(a,b){this.element=this.subject=$(a);this.parent(b);var c=this.cancel.bind(this,!1);if($type(this.element)!="element")this.element=$(this.element.getDocument().body);var d=this.element;this.options.wheelStops&&(this.addEvent("start",function(){d.addEvent("mousewheel",c)},!0),this.addEvent("complete",function(){d.removeEvent("mousewheel",c)},!0))},set:function(){var a=Array.flatten(arguments);this.element.scrollTo(a[0],
a[1])},compute:function(a,b,c){var d=[];(2).times(function(e){d.push(Fx.compute(a[e],b[e],c))});return d},start:function(a,b){if(!this.check(arguments.callee,a,b))return this;var c=this.element.getSize(),d=this.element.getScrollSize(),e=this.element.getScroll(),f={x:a,y:b},g;for(g in f){var h=d[g]-c[g];f[g]=$chk(f[g])?$type(f[g])=="number"?f[g].limit(0,h):h:e[g];f[g]+=this.options.offset[g]}return this.parent([e.x,e.y],[f.x,f.y])},toTop:function(){return this.start(!1,0)},toLeft:function(){return this.start(0,
!1)},toRight:function(){return this.start("right",!1)},toBottom:function(){return this.start(!1,"bottom")},toElement:function(a){a=$(a).getPosition(this.element);return this.start(a.x,a.y)}});
Fx.Elements=new Class({Extends:Fx.CSS,initialize:function(a,b){this.elements=this.subject=$$(a);this.parent(b)},compute:function(a,b,c){var d={},e;for(e in a){var f=a[e],g=b[e],h=d[e]={},i;for(i in f)h[i]=this.parent(f[i],g[i],c)}return d},set:function(a){for(var b in a){var c=a[b],d;for(d in c)this.render(this.elements[b],d,c[d],this.options.unit)}return this},start:function(a){if(!this.check(arguments.callee,a))return this;var b={},c={},d;for(d in a){var e=a[d],f=b[d]={},g=c[d]={},h;for(h in e){var i=
this.prepare(this.elements[d],h,e[h]);f[h]=i.from;g[h]=i.to}}return this.parent(b,c)}});
var Drag=new Class({Implements:[Events,Options],options:{snap:6,unit:"px",grid:!1,style:!0,limit:!1,handle:!1,invert:!1,preventDefault:!1,modifiers:{x:"left",y:"top"}},initialize:function(){var a=Array.link(arguments,{options:Object.type,element:$defined});this.element=$(a.element);this.document=this.element.getDocument();this.setOptions(a.options||{});a=$type(this.options.handle);this.handles=a=="array"||a=="collection"?$$(this.options.handle):$(this.options.handle)||this.element;this.mouse={now:{},
pos:{}};this.value={start:{},now:{}};this.selection=Browser.Engine.trident?"selectstart":"mousedown";this.bound={start:this.start.bind(this),check:this.check.bind(this),drag:this.drag.bind(this),stop:this.stop.bind(this),cancel:this.cancel.bind(this),eventStop:$lambda(!1)};this.attach()},attach:function(){this.handles.addEvent("mousedown",this.bound.start);return this},detach:function(){this.handles.removeEvent("mousedown",this.bound.start);return this},start:function(a){this.options.preventDefault&&
a.preventDefault();this.fireEvent("beforeStart",this.element);this.mouse.start=a.page;var b=this.options.limit;this.limit={x:[],y:[]};for(var c in this.options.modifiers)if(this.options.modifiers[c]&&(this.value.now[c]=this.options.style?this.element.getStyle(this.options.modifiers[c]).toInt():this.element[this.options.modifiers[c]],this.options.invert&&(this.value.now[c]*=-1),this.mouse.pos[c]=a.page[c]-this.value.now[c],b&&b[c]))for(var d=2;d--;)$chk(b[c][d])&&(this.limit[c][d]=$lambda(b[c][d])());
if($type(this.options.grid)=="number")this.options.grid={x:this.options.grid,y:this.options.grid};this.document.addEvents({mousemove:this.bound.check,mouseup:this.bound.cancel});this.document.addEvent(this.selection,this.bound.eventStop)},check:function(a){this.options.preventDefault&&a.preventDefault();Math.round(Math.sqrt(Math.pow(a.page.x-this.mouse.start.x,2)+Math.pow(a.page.y-this.mouse.start.y,2)))>this.options.snap&&(this.cancel(),this.document.addEvents({mousemove:this.bound.drag,mouseup:this.bound.stop}),
this.fireEvent("start",this.element).fireEvent("snap",this.element))},drag:function(a){this.options.preventDefault&&a.preventDefault();this.mouse.now=a.page;for(var b in this.options.modifiers)this.options.modifiers[b]&&(this.value.now[b]=this.mouse.now[b]-this.mouse.pos[b],this.options.invert&&(this.value.now[b]*=-1),this.options.limit&&this.limit[b]&&($chk(this.limit[b][1])&&this.value.now[b]>this.limit[b][1]?this.value.now[b]=this.limit[b][1]:$chk(this.limit[b][0])&&this.value.now[b]<this.limit[b][0]&&
(this.value.now[b]=this.limit[b][0])),this.options.grid[b]&&(this.value.now[b]-=this.value.now[b]%this.options.grid[b]),this.options.style?this.element.setStyle(this.options.modifiers[b],this.value.now[b]+this.options.unit):this.element[this.options.modifiers[b]]=this.value.now[b]);this.fireEvent("drag",this.element)},cancel:function(a){this.document.removeEvent("mousemove",this.bound.check);this.document.removeEvent("mouseup",this.bound.cancel);a&&(this.document.removeEvent(this.selection,this.bound.eventStop),
this.fireEvent("cancel",this.element))},stop:function(a){this.bound.drag(a);this.document.removeEvent(this.selection,this.bound.eventStop);this.document.removeEvent("mousemove",this.bound.drag);this.document.removeEvent("mouseup",this.bound.stop);a&&this.fireEvent("complete",this.element)}});Element.implement({makeResizable:function(a){return new Drag(this,$merge({modifiers:{x:"width",y:"height"}},a))}});
Drag.Move=new Class({Extends:Drag,options:{droppables:[],container:!1},initialize:function(a,b){this.parent(a,b);this.droppables=$$(this.options.droppables);if((this.container=$(this.options.container))&&$type(this.container)!="element")this.container=$(this.container.getDocument().body);var a=this.element,c=a.getStyle("position"),c=c!="static"?c:"absolute";(a.getStyle("left")=="auto"||a.getStyle("top")=="auto")&&a.position(a.getPosition(a.offsetParent));a.setStyle("position",c);this.addEvent("start",
function(){this.checkDroppables()},!0)},start:function(a){if(this.container){var b=this.element,c=this.container,d=c.getCoordinates(b.offsetParent),e={},f={};["top","right","bottom","left"].each(function(a){e[a]=c.getStyle("padding-"+a).toInt();f[a]=b.getStyle("margin-"+a).toInt()},this);this.options.limit={x:[d.left+e.left,d.right-e.right-(b.offsetWidth+f.left+f.right)],y:[d.top+e.top,d.bottom-e.bottom-(b.offsetHeight+f.top+f.bottom)]}}this.parent(a)},checkAgainst:function(a){var a=a.getCoordinates(),
b=this.mouse.now;return b.x>a.left&&b.x<a.right&&b.y<a.bottom&&b.y>a.top},checkDroppables:function(){var a=this.droppables.filter(this.checkAgainst,this).getLast();if(this.overed!=a)this.overed&&this.fireEvent("leave",[this.element,this.overed]),a?(this.overed=a,this.fireEvent("enter",[this.element,a])):this.overed=null},drag:function(a){this.parent(a);this.droppables.length&&this.checkDroppables()},stop:function(a){this.checkDroppables();this.fireEvent("drop",[this.element,this.overed]);this.overed=
null;return this.parent(a)}});Element.implement({makeDraggable:function(a){return new Drag.Move(this,a)}});Hash.Cookie=new Class({Extends:Cookie,options:{autoSave:!0},initialize:function(a,b){this.parent(a,b);this.load()},save:function(){var a=JSON.encode(this.hash);if(!a||a.length>4096)return!1;a=="{}"?this.dispose():this.write(a);return!0},load:function(){this.hash=new Hash(JSON.decode(this.read(),!0));return this}});
Hash.Cookie.implement(function(){var a={};Hash.each(Hash.prototype,function(b,c){a[c]=function(){var a=b.apply(this.hash,arguments);this.options.autoSave&&this.save();return a}});return a}());
var Color=new Native({initialize:function(a,b){arguments.length>=3?(b="rgb",a=Array.slice(arguments,0,3)):typeof a=="string"&&(a=a.match(/rgb/)?a.rgbToHex().hexToRgb(!0):a.match(/hsb/)?a.hsbToRgb():a.hexToRgb(!0));switch(b||"rgb"){case "hsb":var c=a,a=a.hsbToRgb();a.hsb=c;break;case "hex":a=a.hexToRgb(!0)}a.rgb=a.slice(0,3);a.hsb=a.hsb||a.rgbToHsb();a.hex=a.rgbToHex();return $extend(a,this)}});
Color.implement({mix:function(){var a=Array.slice(arguments),b=$type(a.getLast())=="number"?a.pop():50,c=this.slice();a.each(function(a){for(var a=new Color(a),e=0;e<3;e++)c[e]=Math.round(c[e]/100*(100-b)+a[e]/100*b)});return new Color(c,"rgb")},invert:function(){return new Color(this.map(function(a){return 255-a}))},setHue:function(a){return new Color([a,this.hsb[1],this.hsb[2]],"hsb")},setSaturation:function(a){return new Color([this.hsb[0],a,this.hsb[2]],"hsb")},setBrightness:function(a){return new Color([this.hsb[0],
this.hsb[1],a],"hsb")}});function $RGB(a,b,c){return new Color([a,b,c],"rgb")}function $HSB(a,b,c){return new Color([a,b,c],"hsb")}function $HEX(a){return new Color(a,"hex")}
Array.implement({rgbToHsb:function(){var a=this[0],b=this[1],c=this[2],d,e=Math.max(a,b,c),f=e-Math.min(a,b,c);d=e!=0?f/e:0;if(d==0)a=0;else{var g=(e-a)/f,h=(e-b)/f,c=(e-c)/f,a=a==e?c-h:b==e?2+g-c:4+h-g;a/=6;a<0&&a++}return[Math.round(a*360),Math.round(d*100),Math.round(e/255*100)]},hsbToRgb:function(){var a=Math.round(this[2]/100*255);if(this[1]==0)return[a,a,a];else{var b=this[0]%360,c=b%60,d=Math.round(this[2]*(100-this[1])/1E4*255),e=Math.round(this[2]*(6E3-this[1]*c)/6E5*255),c=Math.round(this[2]*
(6E3-this[1]*(60-c))/6E5*255);switch(Math.floor(b/60)){case 0:return[a,c,d];case 1:return[e,a,d];case 2:return[d,a,c];case 3:return[d,e,a];case 4:return[c,d,a];case 5:return[a,d,e]}}return!1}});String.implement({rgbToHsb:function(){return this.match(/\d{1,3}/g)?hsb.rgbToHsb():null},hsbToRgb:function(){var a=this.match(/\d{1,3}/g);return a?a.hsbToRgb():null}});
var Group=new Class({initialize:function(){this.instances=Array.flatten(arguments);this.events={};this.checker={}},addEvent:function(a,b){this.checker[a]=this.checker[a]||{};this.events[a]=this.events[a]||[];if(this.events[a].contains(b))return!1;else this.events[a].push(b);this.instances.each(function(b,d){b.addEvent(a,this.check.bind(this,[a,b,d]))},this);return this},check:function(a,b,c){this.checker[a][c]=!0;this.instances.every(function(b,c){return this.checker[a][c]||!1},this)&&(this.checker[a]=
{},this.events[a].each(function(a){a.call(this,this.instances,b)},this))}}),Asset=new Hash({javascript:function(a,b){var b=$extend({onload:$empty,document:document,check:$lambda(!0)},b),c=new Element("script",{src:a,type:"text/javascript"}),d=b.onload.bind(c),e=b.check,f=b.document;delete b.onload;delete b.check;delete b.document;c.addEvents({load:d,readystatechange:function(){["loaded","complete"].contains(this.readyState)&&d()}}).setProperties(b);if(Browser.Engine.webkit419)var g=function(){$try(e)&&
($clear(g),d())}.periodical(50);return c.inject(f.head)},css:function(a,b){return(new Element("link",$merge({rel:"stylesheet",media:"screen",type:"text/css",href:a},b))).inject(document.head)},image:function(a,b){var b=$merge({onload:$empty,onabort:$empty,onerror:$empty},b),c=new Image,d=$(c)||new Element("img");["load","abort","error"].each(function(a){var f="on"+a,g=b[f];delete b[f];c[f]=function(){var e;if(c){if(!d.parentNode)d.width=c.width,d.height=c.height;e=c.onload=c.onabort=c.onerror=null,
c=e;g.delay(1,d,d);d.fireEvent(a,d,1)}}});c.src=d.src=a;c&&c.complete&&c.onload.delay(1);return d.setProperties(b)},images:function(a,b){b=$merge({onComplete:$empty,onProgress:$empty},b);a.push||(a=[a]);var c=[],d=0;a.each(function(e){var f=new Asset.image(e,{onload:function(){b.onProgress.call(this,d,a.indexOf(e));d++;if(d==a.length)b.onComplete()}});c.push(f)});return new Elements(c)}}),Sortables=new Class({Implements:[Events,Options],options:{snap:4,opacity:1,clone:!1,revert:!1,handle:!1,constrain:!1},
initialize:function(a,b){this.setOptions(b);this.elements=[];this.lists=[];this.idle=!0;this.addLists($$($(a)||a));if(!this.options.clone)this.options.revert=!1;if(this.options.revert)this.effect=new Fx.Morph(null,$merge({duration:250,link:"cancel"},this.options.revert))},attach:function(){this.addLists(this.lists);return this},detach:function(){this.lists=this.removeLists(this.lists);return this},addItems:function(){Array.flatten(arguments).each(function(a){this.elements.push(a);var b=a.retrieve("sortables:start",
this.start.bindWithEvent(this,a));(this.options.handle?a.getElement(this.options.handle)||a:a).addEvent("mousedown",b)},this);return this},addLists:function(){Array.flatten(arguments).each(function(a){this.lists.push(a);this.addItems(a.getChildren())},this);return this},removeItems:function(){var a=[];Array.flatten(arguments).each(function(b){a.push(b);this.elements.erase(b);var c=b.retrieve("sortables:start");(this.options.handle?b.getElement(this.options.handle)||b:b).removeEvent("mousedown",c)},
this);return $$(a)},removeLists:function(){var a=[];Array.flatten(arguments).each(function(b){a.push(b);this.lists.erase(b);this.removeItems(b.getChildren())},this);return $$(a)},getClone:function(a,b){return!this.options.clone?(new Element("div")).inject(document.body):$type(this.options.clone)=="function"?this.options.clone.call(this,a,b,this.list):b.clone(!0).setStyles({margin:"0px",position:"absolute",visibility:"hidden",width:b.getStyle("width")}).inject(this.list).position(b.getPosition(b.getOffsetParent()))},
getDroppables:function(){var a=this.list.getChildren();this.options.constrain||(a=this.lists.concat(a).erase(this.list));return a.erase(this.clone).erase(this.element)},insert:function(a,b){var c="inside";this.lists.contains(b)?(this.list=b,this.drag.droppables=this.getDroppables()):c=this.element.getAllPrevious().contains(b)?"before":"after";this.element.inject(b,c);this.fireEvent("sort",[this.element,this.clone])},start:function(a,b){if(this.idle)this.idle=!1,this.element=b,this.opacity=b.get("opacity"),
this.list=b.getParent(),this.clone=this.getClone(a,b),this.drag=new Drag.Move(this.clone,{snap:this.options.snap,container:this.options.constrain&&this.element.getParent(),droppables:this.getDroppables(),onSnap:function(){a.stop();this.clone.setStyle("visibility","visible");this.element.set("opacity",this.options.opacity||0);this.fireEvent("start",[this.element,this.clone])}.bind(this),onEnter:this.insert.bind(this),onCancel:this.reset.bind(this),onComplete:this.end.bind(this)}),this.clone.inject(this.element,
"before"),this.drag.start(a)},end:function(){this.drag.detach();this.element.set("opacity",this.opacity);if(this.effect){var a=this.element.getStyles("width","height"),b=this.clone.computePosition(this.element.getPosition(this.clone.offsetParent));this.effect.element=this.clone;this.effect.start({top:b.top,left:b.left,width:a.width,height:a.height,opacity:0.25}).chain(this.reset.bind(this))}else this.reset()},reset:function(){this.idle=!0;this.clone.destroy();this.fireEvent("complete",this.element)},
serialize:function(){var a=Array.link(arguments,{modifier:Function.type,index:$defined}),b=this.lists.map(function(b){return b.getChildren().map(a.modifier||function(a){return a.get("id")},this)},this),c=a.index;this.lists.length==1&&(c=0);return $chk(c)&&c>=0&&c<this.lists.length?b[c]:b}}),Tips=new Class({Implements:[Events,Options],options:{onShow:function(a){a.setStyle("visibility","visible")},onHide:function(a){a.setStyle("visibility","hidden")},showDelay:100,hideDelay:100,className:null,offsets:{x:16,
y:16},fixed:!1},initialize:function(){var a=Array.link(arguments,{options:Object.type,elements:$defined});this.setOptions(a.options||null);this.tip=(new Element("div")).inject(document.body);this.options.className&&this.tip.addClass(this.options.className);(new Element("div",{"class":"tip-top"})).inject(this.tip);this.container=(new Element("div",{"class":"tip"})).inject(this.tip);(new Element("div",{"class":"tip-bottom"})).inject(this.tip);this.tip.setStyles({position:"absolute",top:0,left:0,visibility:"hidden"});
a.elements&&this.attach(a.elements)},attach:function(a){$$(a).each(function(a){a.retrieve("tip:title",a.get("title"));a.retrieve("tip:text",a.get("rel")||a.get("href"));var c=a.retrieve("tip:enter",this.elementEnter.bindWithEvent(this,a)),d=a.retrieve("tip:leave",this.elementLeave.bindWithEvent(this,a));a.addEvents({mouseenter:c,mouseleave:d});this.options.fixed||(c=a.retrieve("tip:move",this.elementMove.bindWithEvent(this,a)),a.addEvent("mousemove",c));a.store("tip:native",a.get("title"));a.erase("title")},
this);return this},detach:function(a){$$(a).each(function(a){a.removeEvent("mouseenter",a.retrieve("tip:enter")||$empty);a.removeEvent("mouseleave",a.retrieve("tip:leave")||$empty);a.removeEvent("mousemove",a.retrieve("tip:move")||$empty);a.eliminate("tip:enter").eliminate("tip:leave").eliminate("tip:move");var c=a.retrieve("tip:native");c&&a.set("title",c)});return this},elementEnter:function(a,b){$A(this.container.childNodes).each(Element.dispose);var c=b.retrieve("tip:title");if(c)this.titleElement=
(new Element("div",{"class":"tip-title"})).inject(this.container),this.fill(this.titleElement,c);if(c=b.retrieve("tip:text"))this.textElement=(new Element("div",{"class":"tip-text"})).inject(this.container),this.fill(this.textElement,c);this.timer=$clear(this.timer);this.timer=this.show.delay(this.options.showDelay,this);this.position(!this.options.fixed?a:{page:b.getPosition()})},elementLeave:function(){$clear(this.timer);this.timer=this.hide.delay(this.options.hideDelay,this)},elementMove:function(a){this.position(a)},
position:function(a){var b=window.getSize(),c=window.getScroll(),d={x:this.tip.offsetWidth,y:this.tip.offsetHeight},e={x:"left",y:"top"},f;for(f in e){var g=a.page[f]+this.options.offsets[f];g+d[f]-c[f]>b[f]&&(g=a.page[f]-this.options.offsets[f]-d[f]);this.tip.setStyle(e[f],g)}},fill:function(a,b){typeof b=="string"?a.set("html",b):a.adopt(b)},show:function(){this.fireEvent("show",this.tip)},hide:function(){this.fireEvent("hide",this.tip)}}),SmoothScroll=new Class({Extends:Fx.Scroll,initialize:function(a,
b){var b=b||document,c=b.getDocument(),d=b.getWindow();this.parent(c,a);this.links=this.options.links?$$(this.options.links):$$(c.links);var e=d.location.href.match(/^[^#]*/)[0]+"#";this.links.each(function(a){if(a.href.indexOf(e)==0){var b=a.href.substr(e.length);b&&$(b)&&this.useLink(a,b)}},this);Browser.Engine.webkit419||this.addEvent("complete",function(){d.location.hash=this.anchor},!0)},useLink:function(a,b){a.addEvent("click",function(a){this.anchor=b;this.toElement(b);a.stop()}.bind(this))}}),
Slider=new Class({Implements:[Events,Options],options:{onTick:function(a){this.options.snap&&(a=this.toPosition(this.step));this.knob.setStyle(this.property,a)},snap:!1,offset:0,range:!1,wheel:!1,steps:100,mode:"horizontal"},initialize:function(a,b,c){this.setOptions(c);this.element=$(a);this.knob=$(b);this.previousChange=this.previousEnd=this.step=-1;this.element.addEvent("mousedown",this.clickedElement.bind(this));this.options.wheel&&this.element.addEvent("mousewheel",this.scrolledElement.bindWithEvent(this));
var d,a={},b={x:!1,y:!1};switch(this.options.mode){case "vertical":this.axis="y";this.property="top";d="offsetHeight";break;case "horizontal":this.axis="x",this.property="left",d="offsetWidth"}this.half=this.knob[d]/2;this.full=this.element[d]-this.knob[d]+this.options.offset*2;this.min=$chk(this.options.range[0])?this.options.range[0]:0;this.max=$chk(this.options.range[1])?this.options.range[1]:this.options.steps;this.range=this.max-this.min;this.steps=this.options.steps||this.full;this.stepSize=
Math.abs(this.range)/this.steps;this.stepWidth=this.stepSize*this.full/Math.abs(this.range);this.knob.setStyle("position","relative").setStyle(this.property,-this.options.offset);b[this.axis]=this.property;a[this.axis]=[-this.options.offset,this.full-this.options.offset];this.drag=new Drag(this.knob,{snap:0,limit:a,modifiers:b,onDrag:this.draggedKnob.bind(this),onStart:this.draggedKnob.bind(this),onComplete:function(){this.draggedKnob();this.end()}.bind(this)});if(this.options.snap)this.drag.options.grid=
Math.ceil(this.stepWidth),this.drag.options.limit[this.axis][1]=this.full},set:function(a){if(!(this.range>0^a<this.min))a=this.min;if(!(this.range>0^a>this.max))a=this.max;if(this.step==a)return this;this.step=Math.round(a);this.checkStep();this.end();this.fireEvent("tick",this.toPosition(this.step));return this},clickedElement:function(a){var b=this.range<0?-1:1,a=a.page[this.axis]-this.element.getPosition()[this.axis]-this.half,a=a.limit(-this.options.offset,this.full-this.options.offset);this.step=
Math.round(this.min+b*this.toStep(a));this.checkStep();this.end();this.fireEvent("tick",a)},scrolledElement:function(a){this.set((this.options.mode=="horizontal"?a.wheel<0:a.wheel>0)?this.step-this.stepSize:this.step+this.stepSize);a.stop()},draggedKnob:function(){var a=this.range<0?-1:1,b=this.drag.value.now[this.axis],b=b.limit(-this.options.offset,this.full-this.options.offset);this.step=Math.round(this.min+a*this.toStep(b));this.checkStep()},checkStep:function(){if(this.previousChange!=this.step)this.previousChange=
this.step,this.fireEvent("change",this.step)},end:function(){if(this.previousEnd!==this.step)this.previousEnd=this.step,this.fireEvent("complete",this.step+"")},toStep:function(a){a=(a+this.options.offset)*this.stepSize/this.full*this.steps;return this.options.steps?Math.round(a-a%this.stepSize):a},toPosition:function(a){return this.full*Math.abs(this.min-a)/(this.steps*this.stepSize)-this.options.offset}}),Scroller=new Class({Implements:[Events,Options],options:{area:20,velocity:1,onChange:function(a,
b){this.element.scrollTo(a,b)}},initialize:function(a,b){this.setOptions(b);this.element=$(a);this.listener=$type(this.element)!="element"?$(this.element.getDocument().body):this.element;this.timer=null;this.coord=this.getCoords.bind(this)},start:function(){this.listener.addEvent("mousemove",this.coord)},stop:function(){this.listener.removeEvent("mousemove",this.coord);this.timer=$clear(this.timer)},getCoords:function(a){this.page=this.listener.get("tag")=="body"?a.client:a.page;if(!this.timer)this.timer=
this.scroll.periodical(50,this)},scroll:function(){var a=this.element.getSize(),b=this.element.getScroll(),c=this.element.getPosition(),d={x:0,y:0},e;for(e in this.page)this.page[e]<this.options.area+c[e]&&b[e]!=0?d[e]=(this.page[e]-this.options.area-c[e])*this.options.velocity:this.page[e]+this.options.area>a[e]+c[e]&&a[e]+a[e]!=b[e]&&(d[e]=(this.page[e]-a[e]+this.options.area-c[e])*this.options.velocity);(d.y||d.x)&&this.fireEvent("change",[b.x+d.x,b.y+d.y])}}),Accordion=new Class({Extends:Fx.Elements,
options:{display:0,show:!1,height:!0,width:!1,opacity:!0,fixedHeight:!1,fixedWidth:!1,wait:!1,alwaysHide:!1},initialize:function(){var a=Array.link(arguments,{container:Element.type,options:Object.type,togglers:$defined,elements:$defined});this.parent(a.elements,a.options);this.togglers=$$(a.togglers);this.container=$(a.container);this.previous=-1;if(this.options.alwaysHide)this.options.wait=!0;if($chk(this.options.show))this.options.display=!1,this.previous=this.options.show;if(this.options.start)this.options.display=
!1,this.options.show=!1;this.effects={};if(this.options.opacity)this.effects.opacity="fullOpacity";if(this.options.width)this.effects.width=this.options.fixedWidth?"fullWidth":"offsetWidth";if(this.options.height)this.effects.height=this.options.fixedHeight?"fullHeight":"scrollHeight";for(var a=0,b=this.togglers.length;a<b;a++)this.addSection(this.togglers[a],this.elements[a]);this.elements.each(function(a,b){if(this.options.show===b)this.fireEvent("active",[this.togglers[b],a]);else for(var e in this.effects)a.setStyle(e,
0)},this);$chk(this.options.display)&&this.display(this.options.display)},addSection:function(a,b,c){var a=$(a),b=$(b),d=this.togglers.contains(a),e=this.togglers.length;this.togglers.include(a);this.elements.include(b);e&&(!d||c)?(c=$pick(c,e-1),a.inject(this.togglers[c],"before"),b.inject(a,"after")):this.container&&!d&&(a.inject(this.container),b.inject(this.container));c=this.togglers.indexOf(a);a.addEvent("click",this.display.bind(this,c));this.options.height&&b.setStyles({"padding-top":0,"border-top":"none",
"padding-bottom":0,"border-bottom":"none"});this.options.width&&b.setStyles({"padding-left":0,"border-left":"none","padding-right":0,"border-right":"none"});b.fullOpacity=1;if(this.options.fixedWidth)b.fullWidth=this.options.fixedWidth;if(this.options.fixedHeight)b.fullHeight=this.options.fixedHeight;b.setStyle("overflow","hidden");if(!d)for(var f in this.effects)b.setStyle(f,0);return this},display:function(a){a=$type(a)=="element"?this.elements.indexOf(a):a;if(this.timer&&this.options.wait||a===
this.previous&&!this.options.alwaysHide)return this;this.previous=a;var b={};this.elements.each(function(c,d){b[d]={};var e=d!=a||this.options.alwaysHide&&c.offsetHeight>0;this.fireEvent(e?"background":"active",[this.togglers[d],c]);for(var f in this.effects)b[d][f]=e?0:c[this.effects[f]]},this);return this.start(b)}});
