
package cc.oit.webservice.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ERPOrderSyncService", targetNamespace = "http://www.example.org/erpservice/")
public interface ERPOrderSyncService {


    /**
     * 
     * @param jsonText
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "info", targetNamespace = "")
    @RequestWrapper(localName = "saveSalesOrder", targetNamespace = "http://www.example.org/erpservice/")
    @ResponseWrapper(localName = "saveSalesOrderResponse", targetNamespace = "http://www.example.org/erpservice/")
    public String saveSalesOrder(
        @WebParam(name = "jsonText", targetNamespace = "")
        String jsonText);

    /**
     * 
     * @param jsonText
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "info", targetNamespace = "")
    @RequestWrapper(localName = "saveSalesOrderItem", targetNamespace = "http://www.example.org/erpservice/")
    @ResponseWrapper(localName = "saveSalesOrderItemResponse", targetNamespace = "http://www.example.org/erpservice/")
    public String saveSalesOrderItem(
        @WebParam(name = "jsonText", targetNamespace = "")
        String jsonText);

}
