
package cc.oit.webservice.beans;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ERPService", targetNamespace = "http://www.example.org/erpservice/", wsdlLocation = "http://192.167.36.111:8004/spring-ws/service/ErpService.wsdl")
public class ERPService
    extends Service
{

    private final static URL ERPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ERPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ERPService.class.getResource(".");
            url = new URL(baseUrl, "http://192.167.36.111:8004/spring-ws/service/ErpService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.167.36.111:8004/spring-ws/service/ErpService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ERPSERVICE_WSDL_LOCATION = url;
    }

    public ERPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ERPService() {
        super(ERPSERVICE_WSDL_LOCATION, new QName("http://www.example.org/erpservice/", "ERPService"));
    }

    /**
     * 
     * @return
     *     returns ERPOrderSyncService
     */
    @WebEndpoint(name = "erpServicePort")
    public ERPOrderSyncService getErpServicePort() {
        return super.getPort(new QName("http://www.example.org/erpservice/", "erpServicePort"), ERPOrderSyncService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ERPOrderSyncService
     */
    @WebEndpoint(name = "erpServicePort")
    public ERPOrderSyncService getErpServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/erpservice/", "erpServicePort"), ERPOrderSyncService.class, features);
    }

}
